USE [master]
GO
/****** Object:  Database [TestRecepcionGSC]    Script Date: 08/11/2021 23:28:51 ******/
CREATE DATABASE [TestRecepcionGSC]
 CONTAINMENT = NONE
GO
ALTER DATABASE [TestRecepcionGSC] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestRecepcionGSC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TestRecepcionGSC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET ARITHABORT OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TestRecepcionGSC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TestRecepcionGSC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TestRecepcionGSC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TestRecepcionGSC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET RECOVERY FULL 
GO
ALTER DATABASE [TestRecepcionGSC] SET  MULTI_USER 
GO
ALTER DATABASE [TestRecepcionGSC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TestRecepcionGSC] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TestRecepcionGSC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TestRecepcionGSC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TestRecepcionGSC] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TestRecepcionGSC] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TestRecepcionGSC', N'ON'
GO
ALTER DATABASE [TestRecepcionGSC] SET QUERY_STORE = OFF
GO
